# Generated by Django 4.2.11 on 2024-03-26 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='month_budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('kind', models.CharField(max_length=10)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user')),
            ],
            options={
                'indexes': [models.Index(fields=['UserID', 'year', 'month'], name='app01_month_UserID__371110_idx')],
            },
        ),
    ]
