# Generated by Django 4.2.11 on 2024-03-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock_in',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(max_length=10)),
                ('month', models.IntegerField(max_length=10)),
                ('day', models.IntegerField(max_length=10)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user')),
            ],
        ),
    ]
